-- Sample India Landmarks Data for Seeding
-- Insert these into the places table

INSERT INTO places (name, description, category, city, state, latitude, longitude, entry_fee_adults, entry_fee_children, opening_time, closing_time, best_time_to_visit, image_url, historical_significance, cultural_importance, visitor_rating, review_count)
VALUES
  (
    'Taj Mahal',
    'An ivory-white marble mausoleum on the right bank of the Yamuna river in a vast Mughal garden that encompasses nearly 17 hectares, in Agra. It was built by Mughal emperor Shah Jahan in memory of his favorite wife, Mumtaz Mahal.',
    'Monument',
    'Agra',
    'Uttar Pradesh',
    27.1751,
    78.0421,
    250.00,
    20.00,
    '06:00 AM',
    '06:00 PM',
    'October to March (winter months)',
    'https://images.unsplash.com/photo-1564507592333-c60657e-c60657?w=400',
    'Built in 1652 by Mughal Emperor Shah Jahan as a mausoleum for his wife Mumtaz Mahal. A masterpiece of Mughal architecture.',
    'Symbol of love and one of the Seven Wonders of the World. Represents the pinnacle of Mughal architecture.',
    4.8,
    12500
  ),
  (
    'Red Fort',
    'A historic fort in the city of Delhi. It served as the main residence of the Mughal emperors. Its construction was started in 1638 and completed in 1648.',
    'Fort',
    'Delhi',
    'Delhi',
    28.6562,
    77.2410,
    500.00,
    25.00,
    '09:30 AM',
    '04:30 PM',
    'September to March',
    'https://images.unsplash.com/photo-1564507592333-c60657-c60657?w=400',
    'Built by Mughal Emperor Shah Jahan in 1638. Served as the capital of the Mughal Empire and later the British Indian Empire.',
    'UNESCO World Heritage Site. Symbol of Indian independence and heritage.',
    4.6,
    8900
  ),
  (
    'Golden Temple',
    'A Gurdwara located in Amritsar, Punjab. It is the preeminent spiritual and cultural center of Sikhism. The temple is built around a man-made pool called Amrit Sarovar.',
    'Temple',
    'Amritsar',
    'Punjab',
    31.6200,
    74.8765,
    0.00,
    0.00,
    '04:00 AM',
    '11:00 PM',
    'All year round',
    'https://images.unsplash.com/photo-1564507592333-c60657-c60657?w=400',
    'Founded in 1581 by Guru Arjan Dev. The holiest shrine in Sikhism.',
    'One of the most important pilgrimage sites. Symbol of Sikh faith and community service.',
    4.9,
    15000
  ),
  (
    'Statue of Unity',
    'A colossal statue of Indian independence activist and first Deputy Prime Minister of India, Sardar Vallabhbhai Patel. Located in Gujarat, it is the world''s tallest statue.',
    'Monument',
    'Kevadia',
    'Gujarat',
    21.8404,
    73.7911,
    600.00,
    300.00,
    '08:00 AM',
    '06:00 PM',
    'October to February',
    'https://images.unsplash.com/photo-1564507592333-c60657-c60657?w=400',
    'Inaugurated in 2018. At 182 meters (597 feet), it is the world''s tallest statue.',
    'Honors Sardar Vallabhbhai Patel, who unified India after independence. Modern architectural marvel.',
    4.7,
    5600
  ),
  (
    'Hawa Mahal',
    'A five-story pink sandstone structure built in 1799 in Jaipur. It is one of the most iconic landmarks of Jaipur and was designed to enable royal women to watch street festivals without being seen.',
    'Monument',
    'Jaipur',
    'Rajasthan',
    26.9245,
    75.8267,
    250.00,
    50.00,
    '09:00 AM',
    '05:00 PM',
    'October to February',
    'https://images.unsplash.com/photo-1564507592333-c60657-c60657?w=400',
    'Built in 1799 by Maharaja Sawai Pratap Singh. A masterpiece of Rajasthani architecture.',
    'Symbol of Jaipur''s rich heritage and Rajasthani architecture. UNESCO World Heritage Site.',
    4.5,
    7200
  ),
  (
    'Ram Mandir',
    'An under-construction Hindu temple dedicated to Lord Ram in Ayodhya, Uttar Pradesh. It is one of the most significant pilgrimage sites for Hindus.',
    'Temple',
    'Ayodhya',
    'Uttar Pradesh',
    26.7928,
    82.1933,
    0.00,
    0.00,
    '06:00 AM',
    '12:00 PM',
    'All year round',
    'https://images.unsplash.com/photo-1564507592333-c60657-c60657?w=400',
    'Construction started in 2020. Planned to be a significant spiritual center for Hindus worldwide.',
    'Extremely significant as the birthplace of Lord Ram in Hindu mythology. Major pilgrimage destination.',
    5.0,
    20000
  ),
  (
    'Varanasi Ghats',
    'A series of steps leading down to the Ganges River in Varanasi. The city of Varanasi is one of the oldest continuously inhabited cities in the world and is a major pilgrimage site for Hindus.',
    'Cultural',
    'Varanasi',
    'Uttar Pradesh',
    25.3201,
    82.9850,
    0.00,
    0.00,
    '24/7',
    '24/7',
    'October to November, February to March',
    'https://images.unsplash.com/photo-1564507592333-c60657-c60657?w=400',
    'Over 2,500 years old. One of the holiest cities in Hinduism.',
    'Spiritual heart of Hinduism. The Ghats are centers of spiritual activity and are deeply sacred.',
    4.7,
    9800
  ),
  (
    'Jaipur City Palace',
    'A royal residence of the royal family of Jaipur. The palace is a beautiful blend of Rajasthani and Mughal architecture.',
    'Palace',
    'Jaipur',
    'Rajasthan',
    26.9250,
    75.8232,
    500.00,
    150.00,
    '09:30 AM',
    '05:00 PM',
    'October to February',
    'https://images.unsplash.com/photo-1564507592333-c60657-c60657?w=400',
    'Built in 1729 by Maharaja Sawai Jai Singh II. Still partially a royal residence.',
    'Blend of traditional Rajasthani and Mughal architecture. Symbol of Jaipur''s royal heritage.',
    4.6,
    6500
  ),
  (
    'Mysore Palace',
    'A royal residence in Mysore, India. It is one of the most iconic buildings in India and is often called the ''Versailles of India''.',
    'Palace',
    'Mysore',
    'Karnataka',
    12.3052,
    76.6552,
    600.00,
    250.00,
    '10:00 AM',
    '05:30 PM',
    'October to May',
    'https://images.unsplash.com/photo-1564507592333-c60657-c60657?w=400',
    'Built in 1912 for the royal family of Mysore. Combines Hindu, Mughal, and Gothic architecture.',
    'One of the most visited monuments in India. Symbol of South Indian royal heritage.',
    4.8,
    8700
  ),
  (
    'Gateway of India',
    'A monument built in the year 1924 in Mumbai. It is an arch monument built at the entrance of Mumbai Harbor.',
    'Monument',
    'Mumbai',
    'Maharashtra',
    18.9220,
    72.8347,
    0.00,
    0.00,
    '24/7',
    '24/7',
    'All year round',
    'https://images.unsplash.com/photo-1564507592333-c60657-c60657?w=400',
    'Built in 1924 to commemorate the visit of King George V and Queen Mary. Iconic symbol of Mumbai.',
    'Symbol of Mumbai and India''s independence. One of the most photographed monuments in India.',
    4.6,
    10000
  );

-- Insert sample hotels
INSERT INTO hotels (name, description, city, price_per_night, rating, amenities, is_food_specialty, food_specialty, phone_number)
VALUES
  (
    'The Oberoi Amarvilas',
    'Luxury hotel with a view of the Taj Mahal. Features an award-winning spa and fine dining restaurants.',
    'Agra',
    25000.00,
    4.9,
    ARRAY['WiFi', 'Spa', 'Pool', 'Restaurant', 'Bar', 'Gym'],
    TRUE,
    'Mughlai and North Indian cuisine',
    '+91-562-223-1515'
  ),
  (
    'ITC Maurya',
    'Five-star hotel in Delhi with world-class amenities. Known for its excellent service and fine dining.',
    'Delhi',
    20000.00,
    4.8,
    ARRAY['WiFi', 'Spa', 'Pool', 'Multi-cuisine restaurant', 'Gym', 'Conference rooms'],
    TRUE,
    'Indian, Chinese, and Continental cuisine',
    '+91-11-2611-2233'
  ),
  (
    'Rasa Sarovar Premiere',
    'Boutique hotel near the Golden Temple. Clean and comfortable with traditional Punjabi hospitality.',
    'Amritsar',
    8000.00,
    4.5,
    ARRAY['WiFi', 'Restaurant', 'AC rooms', 'Parking'],
    TRUE,
    'Punjabi cuisine and vegetarian specialties',
    '+91-183-506-1111'
  ),
  (
    'Taj Falaknuma Palace',
    'Luxury heritage hotel in Hyderabad. Former palace with opulent interiors and gourmet dining.',
    'Hyderabad',
    30000.00,
    4.9,
    ARRAY['WiFi', 'Luxury Spa', 'Pool', 'Fine dining', 'Wine cellar', 'Concierge'],
    TRUE,
    'Hyderabadi biryani and international cuisine',
    '+91-40-6629-8585'
  );

-- Insert sample cultural places
INSERT INTO cultural_places (name, description, type, city, is_free, opening_time, closing_time, significance)
VALUES
  (
    'India Gate Park',
    'A public park surrounding the India Gate monument in New Delhi. Popular for evening walks and gatherings.',
    'Garden',
    'Delhi',
    TRUE,
    '06:00 AM',
    '11:00 PM',
    'Popular recreational space in the heart of Delhi'
  ),
  (
    'Jai Vihar Park',
    'A beautiful public park in Jaipur with gardens, walking trails, and family attractions.',
    'Garden',
    'Jaipur',
    TRUE,
    '06:00 AM',
    '09:00 PM',
    'Green space for relaxation and family outings'
  ),
  (
    'National Museum',
    'Located in Delhi, it houses a vast collection of Indian art, historical artifacts, and sculptures.',
    'Museum',
    'Delhi',
    FALSE,
    '10:00 AM',
    '05:00 PM',
    'Showcases India''s rich cultural and historical heritage'
  ),
  (
    'Salarjung Museum',
    'One of the largest museums in India located in Hyderabad. Houses a vast collection of art and artifacts.',
    'Museum',
    'Hyderabad',
    FALSE,
    '10:00 AM',
    '05:00 PM',
    'Treasures of Indian and international art'
  );
